<?php
/**
 * Created by PhpStorm.
 * User: lavannya
 * Date: 29/8/18
 * Time: 3:02 PM
 */

namespace Drupal\amazing_forms\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\UrlHelper;

/**
 * Contribute Form
 */

class ContributeForm extends FormBase{

    public function getFormId()
    {
        // TODO: Implement getFormId() method.
        return 'amazing_forms_contribute_form';
    }

    public function buildForm(array $form, FormStateInterface $form_state)
    {
        // TODO: Implement buildForm() method.
        $form['title'] = array(
            '#type' => 'textfield',
            '#title' => t('Title'),
            '#required' => TRUE,
        );
        $form['video'] = array(
            '#type' => 'textfield',
            '#title' => t('Youtube video'),
        );
        $form['video'] = array(
            '#type' => 'textfield',
            '#title' => t('Youtube video'),
        );
        $form['develop'] = array(
            '#type' => 'checkbox',
            '#title' => t('I would like to be involved in developing this material'),
        );
        $form['description'] = array(
            '#type' => 'textarea',
            '#title' => t('Description'),
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Submit'),
        );
        return $form;
    }

    public function validateForm(array &$form, FormStateInterface $form_state)
    {
//        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
        if (!UrlHelper::isValid($form_state->getValue('video'), TRUE)) {
            $form_state->setErrorByName('video', $this->t("The video url '%url' is invalid.", array('%url' => $form_state->getValue('video'))));
        }
    }

    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        // TODO: Implement submitForm() method.
        // Display result.
        foreach ($form_state->getValues() as $key => $value) {
            drupal_set_message($key . ': ' . $value);
        }
    }
}